---
swagger: "2.0"
info:
  description: "Documentation automatically generated by the <b>swagger-autogen</b>\
    \ module."
  version: "1.0.0"
  title: "CurrencyUomConversionAPI"
host: "localhost:3000"
basePath: "/currency-weight"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /update:
    get:
      tags:
      - "CurrencyUomConversionAPI"
      description: "to fetch the fresh conversion rates"
      operationId: "controllerHandler"
      responses:
        "200":
          description: "API response"
          schema:
            $ref: "#/definitions/conversionRatesResponse"
        "204":
          description: "No data found"
          schema:
            example:
              status:
                statusCode: "204"
                message: "No Content"
        "400":
          description: "Bad Request"
          schema:
            example:
              status:
                statusCode: "400"
                message: "Bad Request"
        "500":
          description: "Internal Server Error"
          schema:
            example:
              status:
                statusCode: "500"
                message: "Internal Server Error"
      x-swagger-router-controller: "ConversionRates.controller"
  /health:
    get:
      tags:
      - "CurrencyUomConversionAPI"
      description: "health check endpoint"
      operationId: "healthCheck"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "API response"
          schema:
            example:
              status: "200"
              messageCode: "API is up and running"
      x-swagger-router-controller: "ConversionRates.controller"
definitions:
  conversionRatesResponse:
    type: "object"
    properties:
      status:
        $ref: "#/definitions/status"
    example:
      status:
        message: "message"
        statusCode: "200"
  status:
    type: "object"
    properties:
      statusCode:
        type: "string"
        enum:
        - "200"
        - "401"
        - "400"
        - "404"
        - "500"
      message:
        type: "string"
    example:
      message: "message"
      statusCode: "200"
  
